# Generated by Django 2.1.4 on 2019-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_num', models.IntegerField()),
                ('defen_num', models.IntegerField()),
                ('speed_num', models.IntegerField()),
            ],
        ),
    ]
