# Generated by Django 2.1.4 on 2019-05-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Army',
        ),
    ]
