# Generated by Django 2.1.4 on 2019-05-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blong_to', models.IntegerField(default=0)),
                ('grade', models.IntegerField()),
                ('hp_num', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_num', models.IntegerField()),
                ('y_num', models.IntegerField()),
                ('blong_to', models.IntegerField(default=0)),
                ('building_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'map',
            },
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('x_num', 'y_num')},
        ),
        migrations.AlterIndexTogether(
            name='map',
            index_together={('blong_to', 'building_id')},
        ),
    ]
