# Generated by Django 2.1.4 on 2019-05-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('x_num', 'y_num')},
        ),
    ]
