# Generated by Django 2.1.4 on 2019-05-21 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='register_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 15, 27, 23, 524205)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_kind',
            field=models.IntegerField(default=None),
        ),
    ]
