# Generated by Django 2.1.4 on 2019-05-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20190521_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='register_datetime',
            field=models.DateTimeField(),
        ),
    ]
